spring.datasource.employee.url=jdbc:h2:mem:employee;DB_CLOSE_DELAY=-1
spring.datasource.employee.username=sa
spring.datasource.employee.password=
spring.datasource.employee.driver-class-name=org.h2.Driver

spring.datasource.dept.url=jdbc:h2:mem:dept;DB_CLOSE_DELAY=-1
spring.datasource.dept.username=sa
spring.datasource.dept.password=
spring.datasource.dept.driver-class-name=org.h2.Driver

# Keep JPA properties generic; each EntityManager config sets ddl-auto
